#! /bin/sh -e

while IFS=: read field value; do
    case "$field" in
        "")
            break
            ;;
        Title)
            # echo strips leading and trailing whitespace
            title=$(echo $value)
            ;;
    esac
done

hsmarkdown | m4 -DTITLE="$title" $1 -
