#! /bin/sh

DESTDIR=${1:-/srv/http/dirtbags.net/contest/2012-02-TF4/photos}

for i in *.jpg; do
	tbase=$DESTDIR/${i%.jpg}
	for size in 100 800; do
		target=$tbase-$size.jpg
		if older $target $i; then
			echo "SCALE $size $i"
			jpegtopnm $i | pamscale -xysize ${size} ${size} | pnmtojpeg > $target
		fi
	done
done

if older $DESTDIR/index.html *.jpg; then
	echo "ALBUM"
	./album.sh . > $DESTDIR/index.html
fi
